config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'application#home'

  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'

  post 'appointment/create', to: 'appointments#create'

  # Only Admin can see Users Index
  resources :users, except: [:index]
  # Patients can only view Doctors' Index and Show Page
  resources :doctors, only: %i[index show]
  # Patients access to web application
  resources :patients, only: %i[new create show] do
    resources :appointments, only: %i[index new create show]
  end

  # Doctors access to web application
  resources :doctors, only: %i[new create show] do
    resources :patients, only: %i[show]
    resources :appointments, only: %i[index show]
  end
  namespace :doctors, only: %i[new create show]  do
    resources :users, only: %i[index show edit update destroy]
    resources :patients, only: %i[show]
    resources :appointments, only: %i[index show]
  end

  # filter Doctors Specialty
  get '/select_specialty', to: 'appointments#select_specialty'
  post '/patients/:patient_id/appointments/new', to: 'appointments#new'

  # Admin privileges
  namespace :admin do
    resources :users, only: %i[index show edit update destroy]
    resources :patients, only: %i[edit update index] do
      match :q, to: 'patients#index', via: :get, on: :collection
    end
    resources :doctors, only: %i[edit update index show]
    resources :appointments, only: %i[edit update destroy index]
  end

  # Doctor privileges
  namespace :doc do
    resources :users, only: %i[index show edit update destroy]
    resources :patients, only: %i[index] do
      match :q, to: 'patients#index', via: :get, on: :collection
    end
    resources :doctors, only: %i[edit update index show]
    resources :appointments, only: %i[edit update index show]
  end

  # namespace :doctors, only: %i[new create show]  do
  #   resources :users, only: %i[index show edit update destroy]
  #   resources :patients, only: %i[show]
  #   resources :appointments, only: %i[index show]
  # end

end

app/models/user.rb
# frozen_string_literal: true

# Password_Controller
class User < ApplicationRecord
  has_secure_password

  has_one :patient
  has_one :doctor

  before_validation :capitalized_name

  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :firstname, presence: true, format: { without: /[0-9]/, message: 'Numbers are not allowed.' }
  validates :lastname, presence: true, format: { without: /[0-9]/, message: 'Numbers are not allowed.' }

  def fullname
    firstname + ' ' + lastname
  end

  def capitalized_name
    self.firstname = firstname.titleize
    self.lastname = lastname.titleize
  end

  def self.patients
    joins(:patient) # for postgres
    # joins(:patient).where("user_id") # for sqlite3
  end

  def self.doctors
    joins(:doctor) # for postgres
    # joins(:doctor).where("user_id") # for sqlite3
  end
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

# User_controller
class Admin::UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  def index
    if !params[:users_type].blank?
      if params[:users_type] == 'Patients'
        @users = User.patients
      elsif params[:users_type] == 'Doctors'
        @users = User.doctors
      end
    else
      @users = User.all.order(firstname: :asc)
    end
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  def edit; end

  def update
    @user.update(user_params)

    if @user.save
      redirect_to admin_user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    @patient = @user.patient
    @doctor = @user.doctor

    if !@patient.nil?
      @user.destroy
      @patient.destroy
    else
      @user.destroy
      @doctor.destroy
    end

    flash[:notice] = 'User deleted.'
    redirect_to admin_users_path
  end

  private

  def set_user
    @user = User.find_by(id: params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :firstname, :lastname,
                                 :admin)
  end
end

app/controllers/doc/appointments_controller.rb
# frozen_string_literal: true

# Appointment_controller
class Doc::AppointmentsController < ApplicationController
  before_action :set_appointment

  def index
    if params[:doctor_id]
      @doctor = Doctor.find_by(id: params[:doctor_id])
      if @doctor.nil? || @doctor != current_doctor
        flash[:alert] = 'Error URL path.'
        redirect_to doc_users_path(current_doctor)
      else
        @appointments = @doctor.appointments
      end
    else
      @appointments = Appointment.all
    end
  end

  def edit; end

  def update
    @appointment.update(appointment_params)

    if @appointment.save
      render :edit
    else
      render :edit
    end
  end

  def destroy
    @user = User.find_by(id: params[:user_id])
    if @user
      @appointment.destroy
      flash[:notice] = 'Appointment deleted.'
      redirect_to doc_users_path(@user)
    else
      flash[:notice] = 'Invalid URL path.'
      redirect_to doc_users_path
    end
  end

  private

  def set_appointment
    @appointment = Appointment.find_by(id: params[:id])
  end

  def appointment_params
    params.require(:appointment).permit(:department, :appointment, :test_results, :treatment_plans,
                                        :prescriptions, :billing)
  end
end

app/controllers/doc/doctors_controller.rb
# frozen_string_literal: true

# Doctors_controller
class Doc::DoctorsController < ApplicationController
  before_action :set_doctor

  def edit; end

  def update
    @doctor.update(doctor_params)

    if @doctor.save
      redirect_to doc_users_path(@doctor.user)
    else
      render :edit
    end
  end

  def show
    @doctor = Doctor.find_by(id: params[:id])
  end

  private

  def set_doctor
    @doctor = Doctor.find_by(id: params[:id])
  end

  def doctor_params
    params.require(:doctor).permit(:user_id, :specialty, :hospital, :reg_no)
  end
end

app/controllers/doc/patients_controller.rb
# frozen_string_literal: true

# Patient_controller
class Doc::PatientsController < ApplicationController
  before_action :set_patient

  def index
    @users = User.patients.where(['firstname LIKE ?', "%#{params[:search]}%"]).page(params[:page]).per(10)
  end

  def edit; end

  def update
    @patient.update(patient_params)

    if @patient.save
      redirect_to doc_users_path(@patient.user)
    else
      render :edit
    end
  end

  def show
    @patient = Patient.find_by(id: params[:id])
  end

  private

  def set_patient
    @patient = Patient.find_by(id: params[:id])
  end

  def patient_params
    params.require(:patient).permit(:user_id, :medical_record, :test_results, :medications,
                                    patient_attributes: %i[firstname])
  end
end

app/controllers/doc/users_controller.rb
# frozen_string_literal: true

# Doctor_Controller
class Doc::UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  def index
    if !params[:users_type].blank?
      if params[:users_type] == 'Patients'
        @users = User.patients
      elsif params[:users_type] == 'Doctors'
        @users = User.doctors
      end
    else
      @users = User.all.order(firstname: :asc)
    end
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  def edit; end

  def update
    @user.update(user_params)

    if @user.save
      redirect_to doc_users_path(@user)
    else
      render :edit
    end
  end

  def destroy
    @patient = @user.patient
    @doctor = @user.doctor

    if !@patient.nil?
      @user.destroy
      @patient.destroy
    else
      @user.destroy
      @doctor.destroy
    end

    flash[:notice] = 'User deleted.'
    redirect_to doc_users_path
  end

  private

  def set_user
    @user = User.find_by(id: params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :firstname, :lastname,
                                 :admin)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      # user as a patient
      if @user.admin == false
        redirect_to new_patient_path
      # user as an admin
      else
        redirect_to admin_users_path
      end
    else
      render :new
    end
  end

  def show
    if @user != current_user
      flash[:alert] = 'Error URL path.'
      redirect_to user_path(current_user)
    end
  end

  def edit
    if @user != current_user
      flash[:alert] = 'Error URL path.'
      redirect_to edit_user_path(current_user)
    end
  end

  def update
    @user.update(user_params)

    if @user.save
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  # user as patient can delete their own profile
  def destroy
    @user.destroy
    current_patient.destroy
    session.clear
    flash[:notice] = 'User deleted, and logging out.'
    redirect_to '/'
  end

  private

  def set_user
    @user = User.find_by(id: params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :firstname, :lastname,
                                 :admin)
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

# User_helper
module UsersHelper
  def date_and_time(datetime)
    datetime.strftime('%A, %B %d, %Y at %l:%M %p')
  end
end

app/views/doc/users/edit.html.erb
<h4>Edit User Profile</h4>

<%= render partial: '/errors', locals: { record: @user } %>

<%= form_with model: [@user], local: true do |f| %>
    <div>
        <%= f.label :firstname, "First Name" %>
        <%= f.text_field :firstname %>
    </div>

    <div>
        <%= f.label :lastname, "Last Name" %>
        <%= f.text_field :lastname %>
    </div>

    <div>
        <%= f.label :username %>
        <%= f.text_field :username %>
    </div>

    <div>
        <%= f.label :email %>
        <%= f.email_field :email %>
    </div>

    <div>
        <%= f.label :password %>
        <%= f.password_field :password %>
    </div>

    <div>
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %>
    </div>

    <br>

    <div>
        <input type="checkbox" id="test5" name="admin" />
        <label for="test5">Is this user an admin?</label>
    </div>

    <br>
    User Information was created at <%= date_and_time(@user.created_at) %><br>
    User Information was updated at <%= date_and_time(@user.updated_at) %><br>
    <br>
    
    <div>
        <%= f.submit "Update User", class: "waves-effect waves-light btn" %>
    </div>
<% end %>

<br>

<%= link_to "Back to User's Profile", doctor_user_path(@user), class: "waves-effect waves-light btn" %>

<br><br>

app/views/doc/users/index.html.erb
<h4>Welcome, <%= current_user.fullname %></h4>
<h6>As a Doctor, you have privileges to access patients, doctors and Appointment information.</h6>
<br>
<br>
<script>
    $(document).ready(function() {
        $('select').material_select();
    });
</script>

app/views/doc/users/show.html.erb
<h4>User Profile</h4>
<b>Fullname: </b><%= @user.fullname %><br>
<b>Username: </b><%= @user.username %><br>
<b>Email: </b><%= @user.email %><br>
<b>Admin: </b><%= @user.admin %><br>
<br>
<%= link_to "Edit Profile", edit_admin_user_path(@user), class: "waves-effect waves-light btn" %>
<br><br>
<%= button_to "Delete User", [:admin, @user], method: :delete, data: {confirm: "Are you sure?"}, class: "waves-effect waves-light btn" %>


<% if @patient = @user.patient %>
    <h4>Patient Information</h4>
    
    <b>Medical Records: </b><%= @patient.medical_record %><br>
    <b>Test Results: </b><%= @patient.test_results %><br>
    <b>Medications: </b><%= @patient.medications %><br>
    <br>
    <%= link_to "Edit Patient Information", edit_admin_patient_path(@patient), class: "waves-effect waves-light btn" %>
    
    <h4>Appointment</h4>
    
    <div class="row">
        <div class="col s12 cards-container">
            <% @patient.appointments.each do |care_team| %>
                <div class="card blue lighten-5">
                    <div class="card-content black-text">
                        <span class="card-title"><%= care_team.doctor.specialty %></span>
                        <p><%= care_team.doctor.fullname %><br>
                        <%= date_time(care_team.appointment) %></p>
                    </div>
                    <div class="card-action" align="center">
                        <%= link_to "Edit Appointment", edit_admin_appointment_path(care_team), class: "waves-effect waves-light btn" %>
                        <br><br>
                        <%= button_to "Delete Appointment", [:admin, care_team], method: :delete, data: {confirm: "Are you sure?"}, params: { 'user_id' => @patient.user }, class: "waves-effect waves-light btn" %>
                    </div>
                </div>  
            <% end %>
        </div>
    </div>

<% elsif @doctor = @user.doctor %>
    <h4>Doctor Information</h4>
    <b>Specialty: </b><%= @doctor.specialty %><br>
    <b>Hospital: </b><%= @doctor.hospital %><br>
    <b>Registration_no: </b><%= @doctor.reg_no %><br>
    <br>
    <%= link_to "Edit Doctor Information", edit_admin_doctor_path(@doctor), class: "waves-effect waves-light btn" %>

    <h4>Patient Lists</h4>

    <div class="row">
        <div class="col s12 cards-container">
            <% @doctor.appointments.each do |care_team| %>
                <div class="card blue lighten-5">
                    <div class="card-content black-text">
                        <span class="card-title"><%= care_team.patient.fullname %></span>
                        <p><%= date_time(care_team.appointment) %></p>
                    </div>
                    <div class="card-action" align="center">
                        <%= link_to "Edit Patient Medical Chart", edit_admin_appointment_path(care_team), class: "waves-effect waves-light btn" %>
                        <br><br>
                        <%= button_to "Delete Care Team", [:admin, care_team], method: :delete, data: {confirm: "Are you sure?"}, params: { 'user_id' => @doctor.user }, class: "waves-effect waves-light btn" %>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
<% end %>