config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'application#home'

  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'

  post 'appointment/create', to: 'appointments#create'

  # Only Admin can see Users Index
  resources :users, except: [:index]
  # Patients can only view Doctors' Index and Show Page
  resources :doctors, only: %i[index show]
  # Patients access to web application
  resources :patients, only: %i[new create show] do
    resources :appointments, only: %i[index new create show]
  end

  # Doctors access to web application
  resources :doctors, only: %i[new create show] do
    resources :patients, only: %i[show]
    resources :appointments, only: %i[index show]
  end
  namespace :doctors, only: %i[new create show]  do
    resources :users, only: %i[index show edit update destroy]
    resources :patients, only: %i[show]
    resources :appointments, only: %i[index show]
  end

  # filter Doctors Specialty
  get '/select_specialty', to: 'appointments#select_specialty'
  post '/patients/:patient_id/appointments/new', to: 'appointments#new'

  # Admin privileges
  namespace :admin do
    resources :users, only: %i[index show edit update destroy]
    resources :patients, only: %i[edit update index] do
      match :q, to: 'patients#index', via: :get, on: :collection
    end
    resources :doctors, only: %i[edit update index show]
    resources :appointments, only: %i[edit update destroy index]
  end

  # Doctor privileges
  namespace :doc do
    resources :users, only: %i[index show edit update destroy]
    resources :patients, only: %i[index] do
      match :q, to: 'patients#index', via: :get, on: :collection
    end
    resources :doctors, only: %i[edit update index show]
    resources :appointments, only: %i[edit update index show]
  end

  # namespace :doctors, only: %i[new create show]  do
  #   resources :users, only: %i[index show edit update destroy]
  #   resources :patients, only: %i[show]
  #   resources :appointments, only: %i[index show]
  # end

end

app/models/patient.rb
# frozen_string_literal: true

# Password_Controller
class Patient < ApplicationRecord
  belongs_to :user
  has_many :appointments
  has_many :doctors, through: :appointments
  accepts_nested_attributes_for :user

  def fullname
    user ? user.fullname : nil
  end
end

app/controllers/admin/patients_controller.rb
# frozen_string_literal: true

# Patient_controller
class Admin::PatientsController < ApplicationController
  before_action :set_patient

  def index
    @users = User.patients.where(['firstname LIKE ?', "%#{params[:search]}%"]).page(params[:page]).per(10)
  end

  def edit; end

  def update
    @patient.update(patient_params)

    if @patient.save
      redirect_to admin_user_path(@patient.user)
    else
      render :edit
    end
  end

  def show
    @patient = Patient.find_by(id: params[:id])
  end

  private

  def set_patient
    @patient = Patient.find_by(id: params[:id])
  end

  def patient_params
    params.require(:patient).permit(:user_id, :medical_record, :test_results, :medications)
  end
end

app/controllers/doc/patients_controller.rb
# frozen_string_literal: true

# Patient_controller
class Doc::PatientsController < ApplicationController
  before_action :set_patient

  def index
    @users = User.patients.where(['firstname LIKE ?', "%#{params[:search]}%"]).page(params[:page]).per(10)
  end

  def edit; end

  def update
    @patient.update(patient_params)

    if @patient.save
      redirect_to doc_users_path(@patient.user)
    else
      render :edit
    end
  end

  def show
    @patient = Patient.find_by(id: params[:id])
  end

  private

  def set_patient
    @patient = Patient.find_by(id: params[:id])
  end

  def patient_params
    params.require(:patient).permit(:user_id, :medical_record, :test_results, :medications,
                                    patient_attributes: %i[firstname])
  end
end

app/controllers/patients_controller.rb
# frozen_string_literal: true

# Patient_Controller

class PatientsController < ApplicationController
  def new
    @patient = Patient.new
  end

  def create
    if current_patient
      current_patient.appointments.build(doctor_id: params[:patient][:doctor_id],
                                         appointment: '2020-12-31 13:05:21', test_results: 'Perfectly healthy', treatment_plans: 'Maintain current BMI', prescriptions: 'None', billing: 0)
      if current_patient.save
        redirect_to patient_path(current_patient)
      else
        render :new
      end
    else
      @patient = Patient.new(patient_params)
      @patient.appointments.build(doctor_id: params[:patient][:doctor_id],
                                  appointment: '2020-12-31 13:05:21', test_results: 'Perfectly healthy', treatment_plans: 'Maintain current BMI', prescriptions: 'None', billing: 0)

      if @patient.save
        redirect_to patient_path(@patient)
      else
        render :new
      end
    end
  end

  # patient main homepage
  def show
    @patient = Patient.find_by(id: params[:id])
    if @patient != current_patient
      flash[:alert] = 'Error URL path.'
      redirect_to patient_path(current_patient)
    end
  end

  private

  def patient_params
    params.require(:patient).permit(:user_id, :medical_record, :test_results, :medications)
  end
end

app/helpers/patients_helper.rb
# frozen_string_literal: true

# Patient_helper
module PatientsHelper
  def twolatest_careteams(patient)
    patient.appointments.order(appointment: :desc).limit(2)
  end
end

app/views/admin/patients/edit.html.erb
<h4>Edit Patient Information </h4>

<%= render partial: '/errors', locals: { record: @patient } %>

<%= form_with model: [:admin, @patient], local: true do |f| %>       
    <div>
        <%= f.label :medical_record, "Medical and Surgical Histories" %>
        <%= f.text_area :medical_record %>
    </div>

    <div>
        <%= f.label :test_results, "Test Results" %>
        <%= f.text_area :test_results %>
    </div>

    <div>
        <%= f.label :medications, "Prescription and Non-Prescription Medications" %>
        <%= f.text_area :medications %>
    </div>

    <br>
    Patient Information was created at <%= date_and_time(@patient.created_at) %><br>
    Patient Information was updated at <%= date_and_time(@patient.updated_at) %><br>
    <br>

    <div>
        <%= f.submit "Update Patient Information", class: "waves-effect waves-light btn" %>
    </div>
<% end %>

<br>

<%= link_to "Back to Patient's Profile", admin_user_path(@patient.user), class: "waves-effect waves-light btn" %>

<br><br>

app/views/admin/patients/index.html.erb
<h5>Search Test</h5>
<div>
    <%= form_tag admin_patients_path, :method => 'get' do %>
        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag "Search" %>
    <% end %>
</div>

<% @users.each do |user| %>
    <table class="highlight">
        <thead>
        
        <tr> <th> Name </th> </tr>
        </thead>
        <tbody>
            <td> <%= user.firstname %> </td>
        </tbody>
    </table>
    <%= paginate @users %>
    <% end %>