config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'application#home'

  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'

  post 'appointment/create', to: 'appointments#create'

  # Only Admin can see Users Index
  resources :users, except: [:index]
  # Patients can only view Doctors' Index and Show Page
  resources :doctors, only: %i[index show]
  # Patients access to web application
  resources :patients, only: %i[new create show] do
    resources :appointments, only: %i[index new create show]
  end

  # Doctors access to web application
  resources :doctors, only: %i[new create show] do
    resources :patients, only: %i[show]
    resources :appointments, only: %i[index show]
  end
  namespace :doctors, only: %i[new create show]  do
    resources :users, only: %i[index show edit update destroy]
    resources :patients, only: %i[show]
    resources :appointments, only: %i[index show]
  end

  # filter Doctors Specialty
  get '/select_specialty', to: 'appointments#select_specialty'
  post '/patients/:patient_id/appointments/new', to: 'appointments#new'

  # Admin privileges
  namespace :admin do
    resources :users, only: %i[index show edit update destroy]
    resources :patients, only: %i[edit update index] do
      match :q, to: 'patients#index', via: :get, on: :collection
    end
    resources :doctors, only: %i[edit update index show]
    resources :appointments, only: %i[edit update destroy index]
  end

  # Doctor privileges
  namespace :doc do
    resources :users, only: %i[index show edit update destroy]
    resources :patients, only: %i[index] do
      match :q, to: 'patients#index', via: :get, on: :collection
    end
    resources :doctors, only: %i[edit update index show]
    resources :appointments, only: %i[edit update index show]
  end

  # namespace :doctors, only: %i[new create show]  do
  #   resources :users, only: %i[index show edit update destroy]
  #   resources :patients, only: %i[show]
  #   resources :appointments, only: %i[index show]
  # end

end

app/models/doctor.rb
# frozen_string_literal: true

# Password_Controller
class Doctor < ApplicationRecord
  belongs_to :user
  has_many :appointments
  has_many :patients, through: :appointments

  scope :general_practice, -> { where(specialty: 'General Practice') }

  def fullname
    user ? user.fullname : nil
  end

  def self.family_medicine
    where(specialty: 'Family Medicine')
  end

  def self.specialties
    select(:specialty).distinct.order(specialty: :asc)
  end

  def self.by_specialty(specialty)
    where(specialty: specialty)
  end
end

app/controllers/admin/doctors_controller.rb
# frozen_string_literal: true

# Doctor_controller
class Admin::DoctorsController < ApplicationController
  before_action :set_doctor

  def edit; end

  def update
    @doctor.update(doctor_params)

    if @doctor.save
      redirect_to admin_user_path(@doctor.user)
    else
      render :edit
    end
  end

  def show
    @doctor = Doctor.find_by(id: params[:id])
  end

  private

  def set_doctor
    @doctor = Doctor.find_by(id: params[:id])
  end

  def doctor_params
    params.require(:doctor).permit(:user_id, :specialty, :hospital, :reg_no)
  end
end

app/controllers/doc/doctors_controller.rb
# frozen_string_literal: true

# Doctors_controller
class Doc::DoctorsController < ApplicationController
  before_action :set_doctor

  def edit; end

  def update
    @doctor.update(doctor_params)

    if @doctor.save
      redirect_to doc_users_path(@doctor.user)
    else
      render :edit
    end
  end

  def show
    @doctor = Doctor.find_by(id: params[:id])
  end

  private

  def set_doctor
    @doctor = Doctor.find_by(id: params[:id])
  end

  def doctor_params
    params.require(:doctor).permit(:user_id, :specialty, :hospital, :reg_no)
  end
end

app/controllers/doctors_controller.rb
# frozen_string_literal: true

# Doctor_controller
class DoctorsController < ApplicationController
  def index
    @doctors = if !params[:specialty].blank?
                 Doctor.by_specialty(params[:specialty])
               else
                 Doctor.all
               end
    @users = User.doctors.where(['firstname LIKE ?', "%#{params[:search]}%"]).page(params[:page]).per(10)
  end

  # admin privilege
  # patient can only view limited Doctor's information
  def show
    @doctor = Doctor.find_by(id: params[:id])
  end
end

app/views/doctors/edit.html.erb
<h4>Edit Doctor Information</h4>

<%= render partial: '/errors', locals: { record: @doctor } %>

<%= form_with model: [:admin, @doctor], local: true do |f| %>
    <div>
        <%= f.label :specialty, "Specialty" %>
        <%= f.text_field :specialty %>
    </div>

    <div>
        <%= f.label :hospital, "Hospital" %>
        <%= f.text_field :hospital %>
    </div>

    <div>
        <%= f.label :reg_no, "Registration No." %>
        <%= f.text_field :reg_no %>
    </div>

    <br>
    Doctor Information was created at <%= date_and_time(@doctor.created_at) %><br>
    Doctor Information was updated at <%= date_and_time(@doctor.updated_at) %><br>
    <br>

    <div>
        <%= f.submit "Update Doctor", class: "waves-effect waves-light btn" %>
    </div>
<% end %>

<br>

<%= link_to "Back to Doctor's Profile", admin_user_path(@doctor.user), class: "waves-effect waves-light btn" %>

<br><br>

app/views/doctors/index.html.erb
<h4>Doctors</h4>
<h5>Filter doctors by specialty:</h5>

<div>
    <%= form_tag("/doctors", method: "get") do %>
<select name="specialty" id="specialty">
<option value="MS">MS</option>
<option value="MD">MD</option>
<option value="Dentist">Dentist</option>
<option value="Physiotherapist">Physiotherapist</option>
</select>
        <br>
        <%= submit_tag "Filter", class: "waves-effect waves-light btn" %>
    <% end %>
</div>
<br>

<% @doctors.order(specialty: :asc).each do |doctor| %>
    <div>
        <i><%= doctor.specialty %></i> | <strong><%= link_to "#{ doctor.fullname }", doctor_path(doctor) %></strong>
    </div>
<% end %>

<br><br><br>
<h5>Search Doctor By First Name</h5>
<div>
    <%= form_tag doctors_path, :method => 'get' do %>
        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag "Search" %>
    <% end %>
</div>
    <table class="highlight">
        <thead>
        <tr> <th> Name </th> </tr>
        </thead>
          <% @users.each do |user| %>
        <tbody>    
            <td> <%= user.firstname %> </td>   
        </tbody>
          <% end %>
    </table>
<%= paginate @users %>














<br><br><br><br>
<script>
    $(document).ready(function() {
        $('select').material_select();
    });
</script>

app/views/doctors/show.html.erb
<h4>Doctor Information</h4>

<b>Fullname: </b><%= @doctor.fullname %><br>
<b>Specialty: </b><%= @doctor.specialty %><br>
<% if current_user.admin == true %>
    <b>Registration_no_no: </b><%= @doctor.reg_no %><br>

    <br>

    <%= link_to "Full Doctor's Profile and Patient Lists", admin_user_path(@doctor.user), class: "waves-effect waves-light btn" %>
<% end %>
<br><br>
<%= link_to "Back to Doctors List", doctors_path, class: "waves-effect waves-light btn" %>
<br>