config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'application#home'

  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'

  post 'appointment/create', to: 'appointments#create'

  # Only Admin can see Users Index
  resources :users, except: [:index]
  # Patients can only view Doctors' Index and Show Page
  resources :doctors, only: %i[index show]
  # Patients access to web application
  resources :patients, only: %i[new create show] do
    resources :appointments, only: %i[index new create show]
  end

  # Doctors access to web application
  resources :doctors, only: %i[new create show] do
    resources :patients, only: %i[show]
    resources :appointments, only: %i[index show]
  end
  namespace :doctors, only: %i[new create show]  do
    resources :users, only: %i[index show edit update destroy]
    resources :patients, only: %i[show]
    resources :appointments, only: %i[index show]
  end

  # filter Doctors Specialty
  get '/select_specialty', to: 'appointments#select_specialty'
  post '/patients/:patient_id/appointments/new', to: 'appointments#new'

  # Admin privileges
  namespace :admin do
    resources :users, only: %i[index show edit update destroy]
    resources :patients, only: %i[edit update index] do
      match :q, to: 'patients#index', via: :get, on: :collection
    end
    resources :doctors, only: %i[edit update index show]
    resources :appointments, only: %i[edit update destroy index]
  end

  # Doctor privileges
  namespace :doc do
    resources :users, only: %i[index show edit update destroy]
    resources :patients, only: %i[index] do
      match :q, to: 'patients#index', via: :get, on: :collection
    end
    resources :doctors, only: %i[edit update index show]
    resources :appointments, only: %i[edit update index show]
  end

  # namespace :doctors, only: %i[new create show]  do
  #   resources :users, only: %i[index show edit update destroy]
  #   resources :patients, only: %i[show]
  #   resources :appointments, only: %i[index show]
  # end

end

app/views/layouts/_navbar.html.erb
<nav>
    <div class="nav-wrapper">
        <a class="brand-logo center">Medi Care</a>
        <a href="#" class="button-collapse"><i class="material-icons">Menu</i></a>
        
        <ul id="nav-mobile" class="right hide-on-med-and-down">
            <% if logged_in? && current_patient %>
                <li><%= link_to "Home", patient_path(current_patient), class: "waves-effect waves-light btn-flat white-text" %></li>
                <li><%= link_to "Appointment", patient_appointments_path(current_patient, current_patient.appointments), class: "waves-effect waves-light btn-flat white-text" %></li>
                <li><%= link_to "Doctors", doctors_path, class: "waves-effect waves-light btn-flat white-text" %></li>
                <li><%= link_to "Profile", user_path(session[:user_id]), class: "waves-effect waves-light btn-flat white-text" %></li>
                <li><%= button_to "Log Out", logout_path, method: "delete", class: "waves-effect waves-light btn-flat white-text" %></li>

            <% elsif logged_in? && current_doctor %>
                <li><%= link_to "Home", doc_users_path, class: "waves-effect waves-light btn-flat white-text" %></li>
                <li><%= link_to "Profile", doc_user_path(current_user.id), class: "waves-effect waves-light btn-flat white-text" %></li>
                <li><%= button_to "Log Out", logout_path, method: "delete", class: "waves-effect waves-light btn-flat white-text" %></li>

            <% elsif logged_in? && current_user.admin == true %>
                <li><%= link_to "Home", admin_users_path, class: "waves-effect waves-light btn-flat white-text" %></li>
                <li><%= link_to "Doctors", doctors_path, class: "waves-effect waves-light btn-flat white-text" %></li>
                <li><%= link_to "Profile", user_path(current_user.id), class: "waves-effect waves-light btn-flat white-text" %></li>
                <li><%= button_to "Log Out", logout_path, method: "delete", class: "waves-effect waves-light btn-flat white-text" %></li>
                
            <% else %>
                <li><%= link_to "Home", root_path, class: "waves-effect waves-light btn-flat white-text" %></li>
                <li><%= link_to "Login", signin_path, class: "waves-effect waves-light btn-flat white-text" %></li>
                <li><%= link_to "Sign Up", new_user_path, class: "waves-effect waves-light btn-flat white-text" %></li>
            <% end %>
        </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlanMyMdVisit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=0.9">

    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script>
      $(document).ready(function () {
        $(".button-collapse").sideNav();
      });
    </script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
  
    <br>

    <main>
      <% flash.each do |type, msg| %>
        <div class="container">
          <div class="chip">
            <%= msg %>
            <i class="close material-icons">close</i>
          </div>
        </div>
      <% end %>
      
      <div class="container">
        <%= yield %>
      </div>
    </main>

    <footer class="page-footer" >
      <div class="container">
        <div class="row">
          <div class="col l6 s12">
            <h5 class="white-text">Medi Care</h5>
            <p class="grey-text text-lighten-4">Stay Safe || Wash Hands || Wear Mask || Repeat</p>
          </div>

          <div class="col l4 offset-l2 s12">
            <h5 class="white-text">Stay Connected</h5>
            <ul>
              <li><a class="grey-text text-lighten-3" target="blank">Medi Care Github</a></li>
              <li><a class="grey-text text-lighten-3" target="blank">Medi Care</a></li>
              <li><a class="grey-text text-lighten-3" target="blank">LinkedIn</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="footer-copyright">
        <div class="container">
          <small>&copy; 2021 <strong>Medi Care</strong></small>
        </div>
      </div>
    </footer>
  </body>
</html>